null, undefined, NaN and -Infinity create holes
d3/d3-contour pull request #61
Opened 2022-07-07 07:59 UTC by Fil

Also, ignore infinite values when computing the thresholds.

closes #49

2022-07-07 12:38 UTC, mbostock commented on src/contours.js
> +        if (v0 == null || isNaN(v0) || !isFinite(v0)) v0 = -1e52;
This…

* is redundant with `low(…)`
* treats positive infinity as negative infinity
* uses a magic number when we can handle infinity exactly

The passed-in `value` should be coerced like this (outside this function, probably in `contour` as I mentioned in the other comment):

```js
value = value === null ? NaN : +value;
if (isNaN(value)) throw new Error(`invalid value: ${value}`);
```

Values we read from `values` should be coerced like this:

```js
v0 = v0 === null ? NaN : +v0;
v1 = v1 === null ? NaN : +v1;
```

Given that, maybe something like this?

```js
const a = value - v0;
const b = v1 - v0;
const d = isFinite(a) && isFinite(b) ? a / b : Math.sign(a) / Math.sign(b);
point[0] = isNaN(d) ? x : x + d - 0.5;
```

2022-07-07 12:44 UTC, mbostock requested changes
Per above comments. Thanks for taking on this work!

2022-07-11 09:27 UTC, Fil commented on src/contours.js
> +      return x == null || isNaN(x) ? false : x >= value;
The scoped version appears to be slightly faster (if anything).

2023-01-08 20:14 UTC, mbostock approved these changes

2023-01-08 20:35 UTC, Fil commented
Thank you! I don't think this needs an addition to README, it's essentially an extension of the "applicability" (or one could say, a bug fix).

2023-01-08 20:35 UTC, merged